### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by jphellemons** [Arrowchain/docs.quiver#38]
Hi can't I just zip my windows `AppData\Roaming\Arrow` folder (except wallet.dat) and put it up as a bootstrap on github? Wouldn't that speed things up?

**Comment by geronimoiceberg** [comment]
Thank you for contacting us. Here are a couple of useful links:

- [The bootstrap](http://explorer.arrowchain.io/Arrow-bootstrap.rar)
- [The Arrow Discord community](https://discord.gg/RdcrR9P)

We're closing this issue because the question is unrelated to the Quiver documentation directly. Please join our Discord for more information about the bootstrap.
